symfony/src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    #[Assert\NotBlank(message:"le titre ne peut pas être vide.")]
    #[Assert\Length(min:3,max:64,maxMessage:"Le titre ne peut dépasser {{ limit }} caractères")]
    private ?string $Titre = null;
    #[ORM\Column(length: 64)]
    private ?string $Auteur = null;

    #[ORM\Column(length: 128)]
    private ?string $link = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }
}

symfony/templates/AddGalerie.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Galerie image!{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="css/AddController.css" /> 
{% endblock %}
{% block body %}
<div id='add'>
    <p>L'image {{image.titre}} à bien été ajouter à la DB</p>
    <details>
        <summary><span class='data_title'>Titre: </span> {{image.titre}}</summary>
        <ul>
            <li><span class='data_title'>Auteur:</span>{{image.auteur}}</li>
            <li><span class='data_title'>Lien:</span>{{image.link}}</li>
        </ul>
        <img src={{image.link}}>
    </details>
</div>
{% endblock %}

symfony/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="{{ asset('css/style.css')}}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
        {% block stylesheets %}

        {% endblock %}
        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="{{ path('app_galerie2') }}">Galerie</a></li>
                <li><a href="{{ path('upload_image') }}">Ajouter une Image</a></li>
                <li><a href="{{ path('app_login') }}">Se connecter</a></li>
                <li><a href="{{ path('app_logout') }}">Déconnexion</a></li>
                <li><a href="{{ path('app_register') }}">Crée un Compte</a></li>

            </ul>
        </nav>

        {% block body %}
            <!-- Le contenu spécifique de chaque page vient ici -->
        {% endblock %}
    </body>
</html>

symfony/templates/gallery.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="{{ asset('css/galerie.css')}}" rel="stylesheet">

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% apply spaceless %}
        <div id='galerie'>
            {% for image in images %}
                <img src="/src/img/{{ image }}">
            {% endfor %}
            {% endapply %}
        </div>
        <br>
        <h1><a href="1">galerie d'image</a></h1><br>
        {% if page_before != -1 %}
            <a href="{{ path('app_galerie', {'page': page_before}) }}">Last Page</a>
        {% else %}
            Page Précédente
        {% endif %}
        {% if page_after != -1 %}
            <a href="{{ path('app_galerie', {'page': page_after }) }}">Page Suivante</a>
        {% else %}
            Next Page
        {% endif %}
    </body>
</html>

symfony/templates/gallery2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Galerie d'images{% endblock %}
{% block stylesheets %}
        <link href="{{ asset('css/galerie.css')}}" rel="stylesheet">
        {% endblock %}
{% block body %}
    <h1><a href="#">galerie d'image</a></h1><br>
    <div id='button'>
        {% if page_before != -1 %}
            <a href="{{ path('app_galerie2', {'page': page_before}) }}">Last Page</a>
        {% else %}
            Page Précédente
        {% endif %}
        {% if page_after != -1 %}
            <a href="{{ path('app_galerie2', {'page': page_after }) }}">Page Suivante</a>
        {% else %}
            Next Page
        {% endif %}
    </div>
    <br>
    <div id='galerie'>
        {% for image in images %}
            <div class='galerie_img'>
                <h2>{{ image.Titre }} par {{ image.auteur }}</h2>
                <img src="{{ image.link }}">
            </div>
        {% endfor %}
    </div>
{% endblock %}

symfony/templates/hello.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HelloWorldController!{% endblock %}

{% block body %}

<div >
    <h1>{{text}}</h1>

    
</div>
{% endblock %}

symfony/templates/image.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une image dans la galerie{% endblock %}

{% block body %}
    <h1>Ajouter une nouvelle image</h1>

    {% for message in app.flashes('réussi') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_row(form.Titre) }}
        {{ form_row(form.Auteur) }}
        {{ form_row(form.fichier) }}
        <button type="submit" class="btn btn-primary">Soumettre</button>
    {{ form_end(form) }}
{% endblock %}

symfony/templates/number.html.twig
{% extends 'base.html.twig' %}
{% block title %}Lucky Number{% endblock %}

{% block body %}
<div>
    <p>Your Lucky Number: <code>{{number}}</code>
</div>

{% endblock %}